### ISSUE TITLE
[BUG] `Text` query doesn't work with `fetch_links=True`

### ISSUE THREAD

**Issue by humbertoortuzar** [roman-right/beanie#606]
**Describe the bug**
Beanie @ 1.20.0
`fetch_links=True` works now with a `.count()` and `.aggregate(...)`, but...
When querying a document with links and a $text statement, the query fails because in the pipeline prefetched lookups are built before the `{$match: {$text: ... }}`. stage. Or at least when using `build_aggregation_pipeline`
```python
def build_aggregation_pipeline(self):
    aggregation_pipeline: List[Dict[str, Any]] = construct_lookup_queries(
        self.document_model
    )

    aggregation_pipeline.append({"$match": self.get_filter_query()})

    sort_pipeline = {"$sort": {i[0]: i[1] for i in self.sort_expressions}}
    if sort_pipeline["$sort"]:
        aggregation_pipeline.append(sort_pipeline)
    if self.skip_number != 0:
        aggregation_pipeline.append({"$skip": self.skip_number})
    if self.limit_number != 0:
        aggregation_pipeline.append({"$limit": self.limit_number})
    return aggregation_pipeline
```

So when you have a `.find(Text(search_query), fetch_links=True)` you get this error:
<img width="968" alt="image" src="https://github.com/roman-right/beanie/assets/53840891/eb1989ff-c512-4013-823a-83c151ed637e">

**To Reproduce**
```python
class ModelB(Document):
    some_field: str = Field(..., description="A field")
    other_field: Optional[str] = Field(None, description="Another field")

class ModelA(Document):
    name: Indexed(str, pymongo.TEXT) = Field(
        ..., description="Name of the ModelA instance."
    )

    model_b: Optional[Link[ModelB]] = Field(
        None, description="Reference to ModelA."
    )

    is_deleted: StrictBool = Field(False, description="Indicates if it's soft deleted")

query_result = await ModelA.find(Text("some text"), fetch_links=True).to_list()

```

**Expected behavior**
It should return a result instead of an error. To do this, `{$match: {$text: ...}}` queries should be included before the `construct_lookup_queries(self.document_model)`

**Additional context**
If anyone else is facing the same, what I'm doing right now is going inside the package to the function mentioned before and printing the stages needed to fetch your links and adding it to a `.aggregate()` query. If you also need to do a $match, you can add that stage to your pipeline.

In terms of the current beanie code, I was able to fix my case (multiple filters, fetch_links, and an aggregate pipeline) by doing this:
```python
def build_aggregation_pipeline(self):
    aggregation_pipeline: List[Dict[str, Any]] = []
    filter_query = self.get_filter_query()
    text_queries = [match_case for match_case in filter_query.get("$and", filter_query) if "$text" in match_case]
    other_queries = [match_case for match_case in filter_query.get("$and", filter_query) if "$text" not in match_case]
    aggregation_pipeline.append({"$match": {"$and": text_queries}})
    aggregation_pipeline += construct_lookup_queries(self.document_model)
    aggregation_pipeline.append({"$match": {"$and": other_queries}})

    sort_pipeline = {"$sort": {i[0]: i[1] for i in self.sort_expressions}}
    ...

```

Disclaimer: This won't work to do $text queries in a linked document, but since $text must be declared first in the pipeline, you'd be better by querying the linked document and using a backlink 👍 .

**Comment by roman-right** [comment]
Hi @humbertoortuzar ,
You are right,
I'll fix this soon. Thank you very much for the catch!

**Comment by roman-right** [comment]
This bug is fixed in https://github.com/roman-right/beanie/pull/669. Please try

**Comment by gsakkis** [comment]
@roman-right `build_aggregation_pipeline` is also called in `FindMany.aggregate` but [only if `fetch_links` is True](https://github.com/roman-right/beanie/blob/main/beanie/odm/queries/find.py#L561-L566). So this fix for `$text` does not apply for aggregates with `fetch_links=False`. The same holds for other `FindMany` stages (`$sort`, `$skip`, `$limit`). It's not obvious to me why these are not taken into account when `fetch_links=False` so perhaps there is a more general bug here but I haven't tested it.

**Comment by MrEarle** [comment]
I believe this is still an issue. I'm using beanie 1.23.

As far as I managed to understand, I believe this happens because in `build_aggregation_pipeline` it does this:

```py
        filter_query = self.get_filter_query()
        if "$text" in filter_query:
            ...
```

But `get_filter_query` joins all filters under an `$and` statement, so the `filter_query` looks like `{'$and': [{'$text': ...}]}`, resulting in `"$text" in filter_query` being false.

**Comment by roman-right** [comment]
Thank you. It will be fixed on the next bug-fixing session.

**Comment by MrEarle** [comment]
I believe this is fixed for `aggregate`, but I missed that `count` didn't use the same code in its implementation. I'll draft a PR to fix the `count` function.

(`count` still doesn't work with text queries and `fetch_links=True`)

**Comment by roman-right** [comment]
This was already fixed in a previous release. The uild_aggregation_pipeline method now uses split_text_query() to separate $text queries and insert them at position 0 (before $lookup stages), while non-text queries are appended after. See the existing tests 	est_text_search and 	est_with_chaining_aggregation_and_text_search in 	ests/odm/test_relations.py.
